function [ fields ] = ANFields( input_args )
%ANFIELDS Summary of this function goes here
%   Detailed explanation goes here

fields = {'ANMom1' ...
        , 'ANMom2' ...
        , 'ANMom3' ...
        , 'Extent' ...
        , 'ANMajorAxisLength' ...
        , 'ANPerimeter' ...
        , 'Solidity'};


end

