function [ fields ] = ANFields( input_args )
%ANFIELDS Summary of this function goes here
%   Detailed explanation goes here

fields = {'ANPerimeter' ...
        , 'num_holes' ...
        , 'Extent' ...
        , 'Eccentricity' ...
        , 'Solidity'};


end

